schema_version: 1

context:
  name: mold
  version: "2.40.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/rui314/mold/archive/v${{ version }}.tar.gz
  sha256: 69414c702ec1084e1fa8ca16da24f167f549e5e11e9ecd5d70a8dcda6f08c249

build:
  number: 4
  skip: win

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake
    - ninja
  host:
    - if: not osx
      then: mimalloc
    - if: not osx
      then: openssl
    - tbb-devel
    - zlib
    - zstd

tests:
  - script:
      - mold --version

about:
  license: MIT
  license_file: LICENSE
  summary: A Modern Linker
  homepage: https://github.com/rui314/mold

extra:
  recipe-maintainers:
    - apmorton
